trigger:
 - main

 pool:
   vmImage: 'windows-2022'

steps:
- task: kiuwan-publisher.kiuwan-analysis-extension.kiuwan-cr-analysis-task.kiuwan-delivery-analysis-task@2
  displayName: 'Kiuwan delivery analysis'
  inputs:
    kiuwanConnection: Kiuwan
    projectnameselector: kiuwanapp
    kiuwanappname: Spiracle