steps:
- task: kiuwan-publisher.kiuwan-analysis-extension.kiuwan-bl-analysis-task.kiuwan-baseline-analysis-task@2
  displayName: 'Kiuwan baseline analysis'
  inputs:
    kiuwanConnection: Kiuwan
    projectnameselector: kiuwanapp
    kiuwanappname: Spiracle