trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
# Starter pipeline
- task: kiuwan-baseline-analysis-task@2
  inputs:
    kiuwanConnection: 'Kiuwan'
    projectnameselector: 'kiuwanapp'
    kiuwanappname: 'Demo'
    includeinsight: true
    uploadsnippets: true
    uploadfiles: false
    skipclones: false
    overridedotkiuwan: false
    overrideappmodel: false
    dbanalysis: false
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
