# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: kiuwan-delivery-analysis-task@2
  inputs:
    kiuwanConnection: 'Kiuwan'
    projectnameselector: 'kiuwanapp'
    kiuwanappname: 'Demo'
    analysisscope: 'completeDelivery'
    includeinsight: true
    failonaudit: true
    uploadsnippets: true
    uploadfiles: false
    skipclones: false
    crstatus: 'resolved'
    overridedotkiuwan: false
    dbanalysis: false